# Generated by Django 5.0.6 on 2024-06-05 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_out_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Как узнал',
                'verbose_name_plural': 'Как узнали',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='StatusLtv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статус LTV',
                'verbose_name_plural': 'Статусы LTV',
            },
        ),
        migrations.CreateModel(
            name='Ltv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth', models.IntegerField(verbose_name='Зубы')),
                ('specialization_cost', models.IntegerField(verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('total', models.IntegerField(verbose_name='Итого')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.service')),
                ('specialization_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialization', verbose_name='Специализация')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.statusltv')),
            ],
            options={
                'verbose_name': 'LTV',
                'verbose_name_plural': 'LTV',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Мобильный телефон')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
                ('find_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.findout', verbose_name='Как узнал')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.gender', verbose_name='Пол')),
                ('ltv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ltv')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
