# Generated by Django 5.0.6 on 2026-05-26 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_add_username_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пайдаланушы', 'verbose_name_plural': 'Пайдаланушылар'},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Ер'), ('F', 'Әйел')], default='', max_length=1, verbose_name='Жынысы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Туған күні'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тегі'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Мобильді телефон'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('mother', 'Ана'), ('father', 'Әке'), ('son', 'Ұлы'), ('daughter', 'Қызы'), ('adoptive_parent', 'Асырап алушы'), ('grandparent', 'Ата ана'), ('adopted_child', 'Асырап алынған бала')], max_length=20, verbose_name='Туыстық')),
                ('iin', models.CharField(blank=True, default='', max_length=12, verbose_name='ЖСН')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Тегі')),
                ('first_name', models.CharField(max_length=255, verbose_name='Аты')),
                ('father_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Әкесінің аты')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Туған күні')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Ер'), ('F', 'Әйел')], default='', max_length=1, verbose_name='Жынысы')),
                ('address', models.TextField(blank=True, default='', verbose_name='Мекенжай')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отбасы мүшесі',
                'verbose_name_plural': 'Отбасы мүшелері',
                'db_table': 'FamilyMember',
                'ordering': ['first_name'],
            },
        ),
    ]
