# Generated by Django 5.0.6 on 2026-05-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['first_name'], 'verbose_name': 'Член семьи', 'verbose_name_plural': 'Члены семьи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='familymember',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='iin',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation_type',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('son', 'Сын'), ('daughter', 'Дочь'), ('adoptive_parent', 'Усыновитель'), ('grandparent', 'Дедушка/Бабушка'), ('adopted_child', 'Усыновлённый ребёнок')], max_length=20, verbose_name='Тип родства'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='oblast',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Область'),
        ),
    ]
