# Generated by Django 5.0.6 on 2026-05-24 13:02

import django.db.models.deletion
import medical.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_user_alter_client_date_of_birth_and_more'),
        ('doctors', '0002_doctors_user_alter_doctors_body'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.TextField(blank=True, default='')),
                ('allergies', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_note', to='client.client')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медицинская заметка',
                'verbose_name_plural': 'Медицинские заметки',
            },
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=medical.models.patient_file_path)),
                ('file_type', models.CharField(choices=[('xray', 'Рентген'), ('photo', 'Фото'), ('document', 'Документ'), ('other', 'Другое')], max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('tooth_number', models.CharField(blank=True, max_length=2, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('linked_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='client.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл пациента',
                'verbose_name_plural': 'Файлы пациентов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(max_length=2)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В процессе'), ('done', 'Завершено'), ('postponed', 'Отложено')], default='planned', max_length=15)),
                ('postpone_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_items', to=settings.AUTH_USER_MODEL)),
                ('linked_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan', to='client.client')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.service')),
            ],
            options={
                'verbose_name': 'Пункт плана лечения',
                'verbose_name_plural': 'Пункты плана лечения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(max_length=2)),
                ('tooth_type', models.CharField(choices=[('permanent', 'Постоянный'), ('primary', 'Молочный')], default='permanent', max_length=10)),
                ('status', models.CharField(choices=[('healthy', 'Здоров'), ('treated', 'Пролечен'), ('urgent', 'Срочно'), ('observation', 'Наблюдение'), ('missing', 'Отсутствует')], default='healthy', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='client.client')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус зуба',
                'verbose_name_plural': 'Статусы зубов',
                'unique_together': {('patient', 'tooth_number')},
            },
        ),
    ]
