# Generated by Django 5.0.6 on 2024-06-05 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Номер кабинета',
                'verbose_name_plural': 'Номера кабинетов',
            },
        ),
        migrations.CreateModel(
            name='PaymentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Состояние оплаты',
                'verbose_name_plural': 'Состояния оплат',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплат',
            },
        ),
        migrations.CreateModel(
            name='RecordingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип записи',
                'verbose_name_plural': 'Типы записей',
            },
        ),
        migrations.CreateModel(
            name='RecordsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(default='default_first_name', max_length=255)),
                ('client_last_name', models.CharField(default='default_last_name', max_length=255)),
                ('client_father_name', models.CharField(blank=True, default='default_father_name', max_length=255, null=True)),
                ('doctors_name', models.CharField(default='default_doctors_name', max_length=255)),
                ('assistant_name', models.CharField(default='default_assistant_name', max_length=255)),
                ('tooth', models.IntegerField(default=0, verbose_name='Зубы')),
                ('specialization_cost', models.IntegerField(default=0, verbose_name='Цена')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('sell', models.IntegerField(default=0, verbose_name='Акции')),
                ('total', models.IntegerField(default=0, verbose_name='Итого')),
                ('registration_date', models.DateField(default='datetime.date.today', verbose_name='Дата приема')),
                ('record_start', models.DateField(default='datetime.date.today', verbose_name='Время начала')),
                ('record_end', models.DateField(default='datetime.date.today', verbose_name='Время окончания')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Причина')),
                ('reception_day', models.DateField(default='datetime.date.today')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.assistant')),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.chairnum', verbose_name='Номер кабинета')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors')),
                ('payment_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.paymentstate', verbose_name='Состояние оплаты')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.paymenttype', verbose_name='Тип оплаты')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.service')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialization', verbose_name='Специализация')),
                ('recording_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.recordingtype', verbose_name='Тип записи')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.status')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
