# Generated by Django 5.2.8 on 2026-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='reception_day',
            field=models.DateField(db_index=True, default='datetime.date.today'),
        ),
    ]
