# Generated by Django 5.0.6 on 2026-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_search_indexes'),
        ('doctors', '0002_doctors_user_alter_doctors_body'),
        ('records', '0004_fix_date_defaults'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['doctor_id', 'client_id'], name='record_doctor_client_idx'),
        ),
    ]
